### ISSUE TITLE
Weird Index Out Of Bounds Exceptions

### ISSUE THREAD

**Issue by PhotonicGluon** [AudiTranscribe/AudiTranscribe#45]
## What is the bug?

When playing audio, suddenly an `IndexOutOfBounds` exception may appear.

## How do you reproduce it?

Unknown how the bug is produced. It appears randomly in the middle of playing audio.

## What is expected?

No exception is to occur.

## What is actually happening?

An exception is occurring.

## [Optional] Screenshots or Screen Recordings

An example exception that is thrown is as shown. It should be noted that the exception is thrown mainly in JavaFX classes, not AudiTranscribe classes.
```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 4
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at javafx.base@20.0.1/com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:88)
	at javafx.base@20.0.1/com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:305)
	at javafx.graphics@20.0.1/javafx.scene.Parent.updateCachedBounds(Parent.java:1705)
	at javafx.graphics@20.0.1/javafx.scene.Parent.recomputeBounds(Parent.java:1649)
	at javafx.graphics@20.0.1/javafx.scene.Parent.doComputeGeomBounds(Parent.java:1502)
	at javafx.graphics@20.0.1/javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at javafx.graphics@20.0.1/com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at javafx.graphics@20.0.1/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at javafx.graphics@20.0.1/com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.graphics@20.0.1/javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3354)
	at javafx.graphics@20.0.1/javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:167)
	at javafx.graphics@20.0.1/com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at javafx.graphics@20.0.1/com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:117)
	at javafx.graphics@20.0.1/javafx.scene.Node.updateGeomBounds(Node.java:3826)
	at javafx.graphics@20.0.1/javafx.scene.Node.getGeomBounds(Node.java:3788)
	at javafx.graphics@20.0.1/javafx.scene.Node.getLocalBounds(Node.java:3736)
	at javafx.graphics@20.0.1/javafx.scene.Node.updateTxBounds(Node.java:3890)
	at javafx.graphics@20.0.1/javafx.scene.Node.getTransformedBounds(Node.java:3682)
	at javafx.graphics@20.0.1/javafx.scene.Node.updateBounds(Node.java:777)
	at javafx.graphics@20.0.1/javafx.scene.Parent.updateBounds(Parent.java:1836)
	at javafx.graphics@20.0.1/javafx.scene.Parent.updateBounds(Parent.java:1834)
	at javafx.graphics@20.0.1/javafx.scene.Parent.updateBounds(Parent.java:1834)
	at javafx.graphics@20.0.1/javafx.scene.Parent.updateBounds(Parent.java:1834)
	at javafx.graphics@20.0.1/javafx.scene.Parent.updateBounds(Parent.java:1834)
	at javafx.graphics@20.0.1/javafx.scene.Parent.updateBounds(Parent.java:1834)
	at javafx.graphics@20.0.1/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2611)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:398)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:427)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:592)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:572)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:565)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@20.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@20.0.1/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoopImpl(Native Method)
	at javafx.graphics@20.0.1/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoop(MacApplication.java:168)
	at javafx.graphics@20.0.1/com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:515)
	at javafx.graphics@20.0.1/com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:648)
	at javafx.graphics@20.0.1/javafx.stage.Stage.showAndWait(Stage.java:469)
	at AudiTranscribe/app.auditranscribe.fxml.views.main.SceneSwitcher.newProjectInTranscriptionScene(SceneSwitcher.java:270)
	at AudiTranscribe/app.auditranscribe.fxml.views.main.SceneSwitcher.startHandler(SceneSwitcher.java:110)
	at AudiTranscribe/app.auditranscribe.MainApplication.start(MainApplication.java:78)
	at javafx.graphics@20.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@20.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```
This exception will be printed over and over again until a forceful termination of the program is done.

## Useful Information

Please complete the following information:

- Operating System: macOS
- Operating System Version: 13.4.1 (22F82)
- Application Version: 0.11.0

**Comment by PhotonicGluon** [comment]
It should also be noted that the exception does **not** appear in any of the logs generated.

**Comment by PhotonicGluon** [comment]
It should be noted that although the exceptions are being generated, the audio continues to play.
