### ISSUE TITLE
Weird Null Pointer Exceptions

### ISSUE THREAD

**Issue by PhotonicGluon** [AudiTranscribe/AudiTranscribe#47]
## What is the Bug?

When playing audio, suddenly a `NullPointerException` may appear.

## How Do You Reproduce It?

Unknown how the bug is produced. It appears randomly in the middle of playing audio.

## What was Expected?

No exception is to occur.

## What is Happening?

An exception is occurring.

An example exception that is thrown is as shown. It should be noted that the exception is thrown mainly in JavaFX classes, not AudiTranscribe classes.
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "javafx.scene.Node.getScene()" because "<local2>" is null
	at javafx.graphics@20.0.1/javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2479)
	at javafx.graphics@20.0.1/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2626)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:398)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:427)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:592)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:572)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:565)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@20.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@20.0.1/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoopImpl(Native Method)
	at javafx.graphics@20.0.1/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoop(MacApplication.java:168)
	at javafx.graphics@20.0.1/com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:515)
	at javafx.graphics@20.0.1/com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:648)
	at javafx.graphics@20.0.1/javafx.stage.Stage.showAndWait(Stage.java:469)
	at AudiTranscribe/app.auditranscribe.fxml.views.main.SceneSwitcher.openProjectInTranscriptionScene(SceneSwitcher.java:411)
	at AudiTranscribe/app.auditranscribe.fxml.views.main.SceneSwitcher.startHandler(SceneSwitcher.java:111)
	at AudiTranscribe/app.auditranscribe.MainApplication.start(MainApplication.java:78)
	at javafx.graphics@20.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@20.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```
This exception will be printed over and over again until a forceful termination of the program is done.

## Additional Context

Please complete the following information:

- **Operating System**: macOS
- **Operating System Version**: 13.4.1 (22F82)
- **Application Version**: 0.11.0

**Comment by PhotonicGluon** [comment]
Unsure if this is related to #45 or if it is a completely different issue altogether.
